### ISSUE TITLE
Please update and release a new version soon.

### ISSUE THREAD

**Issue by Ahbrown41** [couchbase/gocb-opentelemetry#14]
To make this work I had to link to the master branch which is not a best practice.

**Comment by chvck** [comment]
Hi @Ahbrown41, apologies we completely missed updating this with a new release. We release the Go SDK on the third Tuesday of the month so I'll ensure this gets an updated release in October.

**Comment by chvck** [comment]
Hi @Ahbrown41 I've just pushed a new tag, hopefully that's now sorted for you :)
